export const STORAGE_KEYS = {
  CURRENT_READ: 'bible-current-read',
  HIGHLIGHTS: 'bible-highlights',
  STUDIES: 'holy-bible-studies',
  AUTO_BACKUP: 'holy-bible-auto-backup',
  AUTO_BACKUP_FILE_URI: 'holy-bible-auto-backup-file-uri',
  DARK_MODE: '@bible_dark_mode',
  BIBLE_VERSION_GLOBAL: 'holy-bible-version-global',
  VIEW_MODE_VERSION: 'holy-bible-view-mode-version',
  VIEW_MODE_BOOK: 'holy-bible-view-mode-book',
  VIEW_MODE_STUDY_VERSE: 'holy-bible-view-mode-study-verse',
  FONT_SIZE: '@bible_font_size',
  TEXT_ALIGN: '@bible_text_align',
  READER_THEME: '@bible_reader_theme',
  READER_FONT: '@bible_reader_font',
  APP_COLOR_THEME: '@bible_app_color_theme',
  HAPTICS_ENABLED: '@bible_haptics_enabled',
  LAST_ROUTE: 'last_route',
  LAST_ROUTE_PARAMS: 'last_route_params',
  APP_CLEARED: 'app_cleared',
  BIBLE_HISTORY: '@bible_history',
  SEARCH_SCOPE: '@bible:search_scope',
  SEARCH_QUERY: '@bible:search_query',
  SEARCH_HISTORY: '@bible:search_history',
  SEARCH_VERSION: '@bible:search_version',
  SEARCH_BOOK: '@bible:search_book',
  SEARCH_CHAPTER: '@bible:search_chapter',
};
