export const STORAGE_KEYS = {
  LAST_READ: 'bible-last-read',
  HIGHLIGHTS: 'bible-highlights',
  STUDIES: 'holy-bible-studies',
  AUTO_BACKUP: 'holy-bible-auto-backup',
  AUTO_BACKUP_FILE_URI: 'holy-bible-auto-backup-file-uri',
  DARK_MODE: '@bible_dark_mode',
  BIBLE_VERSION_GLOBAL: 'holy-bible-version-global',
  VIEW_MODE_VERSION: 'holy-bible-view-mode-version',
  VIEW_MODE_BOOK: 'holy-bible-view-mode-book',
  VIEW_MODE_STUDY_VERSE: 'holy-bible-view-mode-study-verse',
  FONT_SIZE: '@bible_font_size',
  TEXT_ALIGN: '@bible_text_align',
  READER_THEME: '@bible_reader_theme',
  LAST_ROUTE: 'last_route',
  LAST_ROUTE_PARAMS: 'last_route_params',
};
